# Default values for kafka-config-metrics
replicaCount: 1

image:
  repository: ghcr.io/eladleev/kafka-config-metrics
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""
  labels: {}

podAnnotations: {}
podLabels: {}
deploymentLabels: {}
commonLabels: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 9899
  labels: {}

# Add autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Application specific configuration
kcmConfig:
  global:
    timeout: 3
  
  log:
    format: "text"
    level: "info"
  
  kafka:
    defaultRefreshRate: 60
    minKafkaVersion: "2.8.0"
    adminTimeout: 5
  
  clusters:
    example-cluster:
      brokers:
        - "kafka-broker-1:9092"
        - "kafka-broker-2:9092"
      topicFilter: ""
      tls:
        enabled: false
        # caCert: "/path/to/ca.crt"
        # clientCert: "/path/to/client.crt"
        # clientKey: "/path/to/client.key"
      sasl:
        enabled: false
        usernameEnv: "KAFKA_USERNAME"
        passwordEnv: "KAFKA_PASSWORD"
        mechanism: "PLAIN"