apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-config-metrics.fullname" . }}-cm
  labels:
    {{- include "kafka-config-metrics.labels" . | nindent 4 }}
data:
  kcm.yaml: |
    {{- include "config/kcm.yaml.tpl" . | nindent 4 }}