kind: ConfigMap
metadata:
  name: {{ include "kafka-config-metrics.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
apiVersion: v1
data:
  customconfig.toml:
    {{ include "config/customconfig.toml.tpl" . | quote}}
