{{- if .Values.serviceAccount.create -}}
{{- $commonLabels := .Values.commonLabels -}}
{{- $serviceAccountLabels := default .Values.serviceAccount.labels dict -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-config-metrics.serviceAccountName" . }}
  labels:
    {{- include "kafka-config-metrics.labels" . | nindent 4 }}
    {{- if or $commonLabels $serviceAccountLabels }}
    {{- toYaml (merge $commonLabels $serviceAccountLabels) | nindent 4 | trimSuffix "\n" }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
