{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-config-metrics.serviceAccountName" . }}
  labels:
    {{- include "kafka-config-metrics.labels" . | nindent 4 }}
    {{- $commonLabels := .Values.commonLabels -}}
    {{- $serviceAccountLabels := default .Values.serviceAccount.labels dict -}}
    {{- toYaml (merge $commonLabels $serviceAccountLabels) | nindent 4 | trimSuffix "\n" }}

  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
