name: Release KCM Helm Chart
on:
  push:
    paths:
      - 'charts/**'

jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: helm-check
        uses: igabaydulin/helm-check-action@0.2.1
        env:
          CHART_LOCATION: ./charts/kafka-config-metrics
          CHART_VALUES: ./charts/kafka-config-metrics/values.yaml
  release:
    needs: helm-check
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"