name: Release KCM
on:
  push:
    branches:
      - master
  pull_request:


jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: helm-check
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./charts/kafka-config-metrics
          CHART_VALUES: ./charts/kafka-config-metrics/values.yaml